spring:
  application:
    name: management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tourpresence
    driver-class-name: org.postgresql.Driver
    username: synexis
    password: "synexis123"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080