spring:
  application:
    name: management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tourpresence
    driver-class-name: org.postgresql.Driver
    username: synexis
    password: synexis123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/synexis

server:
  port: 8080
